"""
As tabelas de Application Identifiers do GS1. **Gerado** por
`spec/gerar-tabelas-gs1.py`.

Sao 541 AIs e nao estao escritos a mao de proposito: mais de quinhentos AIs
nao se escrevem de memoria, e um AI com o comprimento errado da um codigo que
se desenha certo e que o leitor le como invalido.

O que cada AI traz, e o que e' que o encoder usa:

- ``formato``    a notacao da GS1, ``N`` numerico, ``X`` alfanumerico,
                 ``Y`` codigo de pais, ``a..20`` variavel;
- ``fixo`` / ``maximo``  o comprimento do **ultimo** componente. Um dos dois
                 e' sempre ``None``, e e' assim que se distingue fixo de
                 variavel sem um booleano a mais.
- ``campos``     todos os componentes, com o mesmo par fixo/maximo.
- ``separador``  se o campo precisa de um FNC1 a separa-lo do seguinte.
                 **E' a razao de existir esta tabela**: sem ela nao se sabe
                 onde acaba ``(10)LOTE-A1`` e onde comeca o campo seguinte.
- ``regex``      o regex do valor, da propria GS1.

A origem e' https://ref.gs1.org/ai/?lang=en.
"""

#: Os AIs, por numero. **As chaves sao cadeias e nao numeros**, porque o
#: AI `01` perde o zero a esquerda quando e' um `int` - e um AI `00` e'
#: diferente do AI `0`, que e' exactamente a razao de o `00` existir.
AIS = {
    '00': {'formato': "N2+N18", 'fixo': 18, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 18, "maximo": None},), 'separador': False, 'regex': "(\\d{18})"},
    '01': {'formato': "N2+N14", 'fixo': 14, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 14, "maximo": None},), 'separador': False, 'regex': "(\\d{14})"},
    '02': {'formato': "N2+N14", 'fixo': 14, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 14, "maximo": None},), 'separador': False, 'regex': "(\\d{14})"},
    '03': {'formato': "N2+N14", 'fixo': 14, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 14, "maximo": None},), 'separador': False, 'regex': "(\\d{14})"},
    '10': {'formato': "N2+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '11': {'formato': "N2+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))"},
    '12': {'formato': "N2+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))"},
    '13': {'formato': "N2+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))"},
    '15': {'formato': "N2+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))"},
    '16': {'formato': "N2+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))"},
    '17': {'formato': "N2+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))"},
    '20': {'formato': "N2+N2", 'fixo': 2, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 2, "maximo": None},), 'separador': False, 'regex': "(\\d{2})"},
    '21': {'formato': "N2+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '22': {'formato': "N2+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '235': {'formato': "N3+X..28", 'fixo': None, 'maximo': 28, 'campos': ({"tipo": "X", "fixo": None, "maximo": 28},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,28})"},
    '240': {'formato': "N3+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '241': {'formato': "N3+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '242': {'formato': "N3+N..6", 'fixo': None, 'maximo': 6, 'campos': ({"tipo": "N", "fixo": None, "maximo": 6},), 'separador': True, 'regex': "(\\d{1,6})"},
    '243': {'formato': "N3+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '250': {'formato': "N3+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '251': {'formato': "N3+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '253': {'formato': "N3+N13[+X..17]", 'fixo': None, 'maximo': 17, 'campos': ({"tipo": "N", "fixo": 13, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 17},), 'separador': True, 'regex': "(\\d{13})([!%-?A-Z_a-z\\x22]{0,17})"},
    '254': {'formato': "N3+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '255': {'formato': "N3+N13[+N..12]", 'fixo': None, 'maximo': 12, 'campos': ({"tipo": "N", "fixo": 13, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 12},), 'separador': True, 'regex': "(\\d{13})(\\d{0,12})"},
    '30': {'formato': "N2+N..8", 'fixo': None, 'maximo': 8, 'campos': ({"tipo": "N", "fixo": None, "maximo": 8},), 'separador': True, 'regex': "(\\d{0,8})"},
    '3100': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3101': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3102': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3103': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3104': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3105': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3110': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3111': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3112': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3113': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3114': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3115': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3120': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3121': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3122': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3123': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3124': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3125': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3130': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3131': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3132': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3133': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3134': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3135': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3140': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3141': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3142': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3143': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3144': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3145': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3150': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3151': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3152': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3153': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3154': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3155': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3160': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3161': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3162': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3163': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3164': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3165': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3200': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3201': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3202': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3203': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3204': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3205': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3210': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3211': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3212': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3213': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3214': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3215': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3220': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3221': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3222': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3223': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3224': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3225': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3230': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3231': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3232': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3233': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3234': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3235': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3240': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3241': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3242': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3243': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3244': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3245': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3250': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3251': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3252': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3253': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3254': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3255': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3260': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3261': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3262': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3263': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3264': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3265': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3270': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3271': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3272': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3273': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3274': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3275': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3280': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3281': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3282': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3283': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3284': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3285': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3290': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3291': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3292': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3293': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3294': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3295': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3300': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3301': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3302': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3303': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3304': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3305': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3310': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3311': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3312': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3313': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3314': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3315': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3320': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3321': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3322': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3323': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3324': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3325': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3330': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3331': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3332': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3333': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3334': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3335': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3340': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3341': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3342': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3343': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3344': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3345': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3350': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3351': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3352': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3353': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3354': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3355': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3360': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3361': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3362': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3363': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3364': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3365': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3370': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3371': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3372': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3373': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3374': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3375': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3400': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3401': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3402': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3403': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3404': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3405': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3410': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3411': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3412': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3413': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3414': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3415': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3420': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3421': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3422': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3423': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3424': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3425': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3430': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3431': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3432': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3433': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3434': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3435': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3440': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3441': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3442': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3443': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3444': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3445': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3450': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3451': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3452': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3453': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3454': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3455': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3460': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3461': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3462': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3463': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3464': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3465': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3470': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3471': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3472': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3473': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3474': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3475': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3480': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3481': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3482': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3483': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3484': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3485': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3490': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3491': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3492': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3493': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3494': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3495': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3500': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3501': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3502': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3503': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3504': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3505': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3510': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3511': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3512': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3513': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3514': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3515': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3520': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3521': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3522': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3523': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3524': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3525': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3530': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3531': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3532': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3533': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3534': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3535': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3540': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3541': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3542': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3543': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3544': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3545': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3550': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3551': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3552': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3553': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3554': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3555': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3560': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3561': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3562': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3563': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3564': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3565': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3570': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3571': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3572': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3573': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3574': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3575': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3600': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3601': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3602': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3603': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3604': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3605': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3610': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3611': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3612': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3613': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3614': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3615': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3620': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3621': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3622': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3623': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3624': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3625': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3630': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3631': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3632': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3633': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3634': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3635': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3640': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3641': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3642': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3643': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3644': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3645': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3650': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3651': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3652': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3653': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3654': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3655': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3660': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3661': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3662': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3663': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3664': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3665': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3670': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3671': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3672': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3673': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3674': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3675': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3680': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3681': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3682': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3683': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3684': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3685': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3690': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3691': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3692': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3693': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3694': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '3695': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': False, 'regex': "(\\d{6})"},
    '37': {'formato': "N2+N..8", 'fixo': None, 'maximo': 8, 'campos': ({"tipo": "N", "fixo": None, "maximo": 8},), 'separador': True, 'regex': "(\\d{1,8})"},
    '3900': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3901': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3902': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3903': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3904': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3905': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3906': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3907': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3908': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3909': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3910': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3911': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3912': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3913': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3914': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3915': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3916': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3917': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3918': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3919': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3920': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3921': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3922': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3923': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3924': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3925': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3926': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3927': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3928': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3929': {'formato': "N4+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{1,15})"},
    '3930': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3931': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3932': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3933': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3934': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3935': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3936': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3937': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3938': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3939': {'formato': "N4+N3+N..15", 'fixo': None, 'maximo': 15, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 15},), 'separador': True, 'regex': "(\\d{3})(\\d{1,15})"},
    '3940': {'formato': "N4+N4", 'fixo': 4, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 4, "maximo": None},), 'separador': True, 'regex': "(\\d{4})"},
    '3941': {'formato': "N4+N4", 'fixo': 4, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 4, "maximo": None},), 'separador': True, 'regex': "(\\d{4})"},
    '3942': {'formato': "N4+N4", 'fixo': 4, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 4, "maximo": None},), 'separador': True, 'regex': "(\\d{4})"},
    '3943': {'formato': "N4+N4", 'fixo': 4, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 4, "maximo": None},), 'separador': True, 'regex': "(\\d{4})"},
    '3950': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6})"},
    '3951': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6})"},
    '3952': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6})"},
    '3953': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6})"},
    '3954': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6})"},
    '3955': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6})"},
    '400': {'formato': "N3+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '401': {'formato': "N3+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '402': {'formato': "N3+N17", 'fixo': 17, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 17, "maximo": None},), 'separador': True, 'regex': "(\\d{17})"},
    '403': {'formato': "N3+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '410': {'formato': "N3+N13", 'fixo': 13, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 13, "maximo": None},), 'separador': False, 'regex': "(\\d{13})"},
    '411': {'formato': "N3+N13", 'fixo': 13, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 13, "maximo": None},), 'separador': False, 'regex': "(\\d{13})"},
    '412': {'formato': "N3+N13", 'fixo': 13, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 13, "maximo": None},), 'separador': False, 'regex': "(\\d{13})"},
    '413': {'formato': "N3+N13", 'fixo': 13, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 13, "maximo": None},), 'separador': False, 'regex': "(\\d{13})"},
    '414': {'formato': "N3+N13", 'fixo': 13, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 13, "maximo": None},), 'separador': False, 'regex': "(\\d{13})"},
    '415': {'formato': "N3+N13", 'fixo': 13, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 13, "maximo": None},), 'separador': False, 'regex': "(\\d{13})"},
    '416': {'formato': "N3+N13", 'fixo': 13, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 13, "maximo": None},), 'separador': False, 'regex': "(\\d{13})"},
    '417': {'formato': "N3+N13", 'fixo': 13, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 13, "maximo": None},), 'separador': False, 'regex': "(\\d{13})"},
    '420': {'formato': "N3+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '421': {'formato': "N3+N3+X..9", 'fixo': None, 'maximo': 9, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 9},), 'separador': True, 'regex': "(\\d{3})([!%-?A-Z_a-z\\x22]{1,9})"},
    '422': {'formato': "N3+N3", 'fixo': 3, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None},), 'separador': True, 'regex': "(\\d{3})"},
    '423': {'formato': "N3+N3+N..12", 'fixo': None, 'maximo': 12, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 12},), 'separador': True, 'regex': "((?:\\d{3}){1,5})"},
    '424': {'formato': "N3+N3", 'fixo': 3, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None},), 'separador': True, 'regex': "(\\d{3})"},
    '425': {'formato': "N3+N3+N..12", 'fixo': None, 'maximo': 12, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 12},), 'separador': True, 'regex': "((?:\\d{3}){1,5})"},
    '426': {'formato': "N3+N3", 'fixo': 3, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None},), 'separador': True, 'regex': "(\\d{3})"},
    '427': {'formato': "N3+X..3", 'fixo': None, 'maximo': 3, 'campos': ({"tipo": "X", "fixo": None, "maximo": 3},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,3})"},
    '4300': {'formato': "N4+X..35", 'fixo': None, 'maximo': 35, 'campos': ({"tipo": "X", "fixo": None, "maximo": 35},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})"},
    '4301': {'formato': "N4+X..35", 'fixo': None, 'maximo': 35, 'campos': ({"tipo": "X", "fixo": None, "maximo": 35},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})"},
    '4302': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})"},
    '4303': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})"},
    '4304': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})"},
    '4305': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})"},
    '4306': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})"},
    '4307': {'formato': "N4+X2", 'fixo': 2, 'maximo': None, 'campos': ({"tipo": "X", "fixo": 2, "maximo": None},), 'separador': True, 'regex': "([A-Z0-9]{2})"},
    '4308': {'formato': "N4+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '4309': {'formato': "N4+N20", 'fixo': 20, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 20, "maximo": None},), 'separador': True, 'regex': "(\\d{20})"},
    '4310': {'formato': "N4+X..35", 'fixo': None, 'maximo': 35, 'campos': ({"tipo": "X", "fixo": None, "maximo": 35},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})"},
    '4311': {'formato': "N4+X..35", 'fixo': None, 'maximo': 35, 'campos': ({"tipo": "X", "fixo": None, "maximo": 35},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})"},
    '4312': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})"},
    '4313': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})"},
    '4314': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})"},
    '4315': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})"},
    '4316': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})"},
    '4317': {'formato': "N4+X2", 'fixo': 2, 'maximo': None, 'campos': ({"tipo": "X", "fixo": 2, "maximo": None},), 'separador': True, 'regex': "([A-Z0-9]{2})"},
    '4318': {'formato': "N4+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '4319': {'formato': "N4+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '4320': {'formato': "N4+X..35", 'fixo': None, 'maximo': 35, 'campos': ({"tipo": "X", "fixo": None, "maximo": 35},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})"},
    '4321': {'formato': "N4+N1", 'fixo': 1, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 1, "maximo": None},), 'separador': True, 'regex': "([01])"},
    '4322': {'formato': "N4+N1", 'fixo': 1, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 1, "maximo": None},), 'separador': True, 'regex': "([01])"},
    '4323': {'formato': "N4+N1", 'fixo': 1, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 1, "maximo": None},), 'separador': True, 'regex': "([01])"},
    '4324': {'formato': "N4+N10", 'fixo': 10, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 10, "maximo": None},), 'separador': True, 'regex': "(\\d{10})"},
    '4325': {'formato': "N4+N10", 'fixo': 10, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 10, "maximo": None},), 'separador': True, 'regex': "(\\d{10})"},
    '4326': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6})"},
    '4330': {'formato': "N4+N6+[-]", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6}[-]?)"},
    '4331': {'formato': "N4+N6+[-]", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6}[-]?)"},
    '4332': {'formato': "N4+N6+[-]", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6}[-]?)"},
    '4333': {'formato': "N4+N6+[-]", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6}[-]?)"},
    '7001': {'formato': "N4+N13", 'fixo': 13, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 13, "maximo": None},), 'separador': True, 'regex': "(\\d{13})"},
    '7002': {'formato': "N4+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '7003': {'formato': "N4+N10", 'fixo': 10, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 10, "maximo": None},), 'separador': True, 'regex': "(\\d{10})"},
    '7004': {'formato': "N4+N..4", 'fixo': None, 'maximo': 4, 'campos': ({"tipo": "N", "fixo": None, "maximo": 4},), 'separador': True, 'regex': "(\\d{0,4})"},
    '7005': {'formato': "N4+X..12", 'fixo': None, 'maximo': 12, 'campos': ({"tipo": "X", "fixo": None, "maximo": 12},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,12})"},
    '7006': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6})"},
    '7007': {'formato': "N4+N6[+N6]", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None}, {"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6})(\\d{6})?"},
    '7008': {'formato': "N4+X..3", 'fixo': None, 'maximo': 3, 'campos': ({"tipo": "X", "fixo": None, "maximo": 3},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,3})"},
    '7009': {'formato': "N4+X..10", 'fixo': None, 'maximo': 10, 'campos': ({"tipo": "X", "fixo": None, "maximo": 10},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,10})"},
    '7010': {'formato': "N4+X..2", 'fixo': None, 'maximo': 2, 'campos': ({"tipo": "X", "fixo": None, "maximo": 2},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,2})"},
    '7011': {'formato': "N4+N6[+N4]", 'fixo': 4, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None}, {"tipo": "N", "fixo": 4, "maximo": None},), 'separador': True, 'regex': "(\\d{6})(\\d{4})?"},
    '7020': {'formato': "N4+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '7021': {'formato': "N4+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '7022': {'formato': "N4+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '7023': {'formato': "N4+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '7030': {'formato': "N4+N3+X..27", 'fixo': None, 'maximo': 27, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 27},), 'separador': True, 'regex': "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})"},
    '7031': {'formato': "N4+N3+X..27", 'fixo': None, 'maximo': 27, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 27},), 'separador': True, 'regex': "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})"},
    '7032': {'formato': "N4+N3+X..27", 'fixo': None, 'maximo': 27, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 27},), 'separador': True, 'regex': "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})"},
    '7033': {'formato': "N4+N3+X..27", 'fixo': None, 'maximo': 27, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 27},), 'separador': True, 'regex': "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})"},
    '7034': {'formato': "N4+N3+X..27", 'fixo': None, 'maximo': 27, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 27},), 'separador': True, 'regex': "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})"},
    '7035': {'formato': "N4+N3+X..27", 'fixo': None, 'maximo': 27, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 27},), 'separador': True, 'regex': "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})"},
    '7036': {'formato': "N4+N3+X..27", 'fixo': None, 'maximo': 27, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 27},), 'separador': True, 'regex': "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})"},
    '7037': {'formato': "N4+N3+X..27", 'fixo': None, 'maximo': 27, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 27},), 'separador': True, 'regex': "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})"},
    '7038': {'formato': "N4+N3+X..27", 'fixo': None, 'maximo': 27, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 27},), 'separador': True, 'regex': "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})"},
    '7039': {'formato': "N4+N3+X..27", 'fixo': None, 'maximo': 27, 'campos': ({"tipo": "N", "fixo": 3, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 27},), 'separador': True, 'regex': "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})"},
    '7040': {'formato': "N4+N1+X3", 'fixo': 3, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 1, "maximo": None}, {"tipo": "X", "fixo": 3, "maximo": None},), 'separador': True, 'regex': "(\\d)([!%-?A-Z_a-z\\x22])([!%-?A-Z_a-z\\x22])([!%-?A-Z_a-z\\x22])"},
    '7041': {'formato': "N4+X..4", 'fixo': None, 'maximo': 4, 'campos': ({"tipo": "X", "fixo": None, "maximo": 4},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,4})"},
    '710': {'formato': "N3+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '711': {'formato': "N3+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '712': {'formato': "N3+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '713': {'formato': "N3+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '714': {'formato': "N3+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '715': {'formato': "N3+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '716': {'formato': "N3+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '717': {'formato': "N3+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '7230': {'formato': "N4+X2+X..28", 'fixo': None, 'maximo': 28, 'campos': ({"tipo": "X", "fixo": 2, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 28},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{3,30})"},
    '7231': {'formato': "N4+X2+X..28", 'fixo': None, 'maximo': 28, 'campos': ({"tipo": "X", "fixo": 2, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 28},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{3,30})"},
    '7232': {'formato': "N4+X2+X..28", 'fixo': None, 'maximo': 28, 'campos': ({"tipo": "X", "fixo": 2, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 28},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{3,30})"},
    '7233': {'formato': "N4+X2+X..28", 'fixo': None, 'maximo': 28, 'campos': ({"tipo": "X", "fixo": 2, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 28},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{3,30})"},
    '7234': {'formato': "N4+X2+X..28", 'fixo': None, 'maximo': 28, 'campos': ({"tipo": "X", "fixo": 2, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 28},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{3,30})"},
    '7235': {'formato': "N4+X2+X..28", 'fixo': None, 'maximo': 28, 'campos': ({"tipo": "X", "fixo": 2, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 28},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{3,30})"},
    '7236': {'formato': "N4+X2+X..28", 'fixo': None, 'maximo': 28, 'campos': ({"tipo": "X", "fixo": 2, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 28},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{3,30})"},
    '7237': {'formato': "N4+X2+X..28", 'fixo': None, 'maximo': 28, 'campos': ({"tipo": "X", "fixo": 2, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 28},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{3,30})"},
    '7238': {'formato': "N4+X2+X..28", 'fixo': None, 'maximo': 28, 'campos': ({"tipo": "X", "fixo": 2, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 28},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{3,30})"},
    '7239': {'formato': "N4+X2+X..28", 'fixo': None, 'maximo': 28, 'campos': ({"tipo": "X", "fixo": 2, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 28},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{3,30})"},
    '7240': {'formato': "N4+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '7241': {'formato': "N4+N2", 'fixo': 2, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 2, "maximo": None},), 'separador': True, 'regex': "(\\d{2})"},
    '7242': {'formato': "N4+X..25", 'fixo': None, 'maximo': 25, 'campos': ({"tipo": "X", "fixo": None, "maximo": 25},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,25})"},
    '7250': {'formato': "N4+N8", 'fixo': 8, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 8, "maximo": None},), 'separador': True, 'regex': "(\\d{4}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))"},
    '7251': {'formato': "N4+N12", 'fixo': 12, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 12, "maximo": None},), 'separador': True, 'regex': "(\\d{4}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01])(?:[01]\\d|2[0-3])(?:[0-5]\\d))"},
    '7252': {'formato': "N4+N1", 'fixo': 1, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 1, "maximo": None},), 'separador': True, 'regex': "(\\d{1})"},
    '7253': {'formato': "N4+X..40", 'fixo': None, 'maximo': 40, 'campos': ({"tipo": "X", "fixo": None, "maximo": 40},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,40})"},
    '7254': {'formato': "N4+X..40", 'fixo': None, 'maximo': 40, 'campos': ({"tipo": "X", "fixo": None, "maximo": 40},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,40})"},
    '7255': {'formato': "N4+X..10", 'fixo': None, 'maximo': 10, 'campos': ({"tipo": "X", "fixo": None, "maximo": 10},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,10})"},
    '7256': {'formato': "N4+X..90", 'fixo': None, 'maximo': 90, 'campos': ({"tipo": "X", "fixo": None, "maximo": 90},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,90})"},
    '7257': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})"},
    '7258': {'formato': "N4+N1+X1+N1", 'fixo': 1, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 1, "maximo": None}, {"tipo": "X", "fixo": 1, "maximo": None}, {"tipo": "N", "fixo": 1, "maximo": None},), 'separador': True, 'regex': "(\\d[/]\\d)"},
    '7259': {'formato': "N4+X..40", 'fixo': None, 'maximo': 40, 'campos': ({"tipo": "X", "fixo": None, "maximo": 40},), 'separador': True, 'regex': "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,40})"},
    '8001': {'formato': "N4+N14", 'fixo': 14, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 14, "maximo": None},), 'separador': True, 'regex': "(\\d{4})(\\d{5})(\\d{3})(\\d{1})(\\d{1})"},
    '8002': {'formato': "N4+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '8003': {'formato': "N4+N14[+X..16]", 'fixo': None, 'maximo': 16, 'campos': ({"tipo": "N", "fixo": 14, "maximo": None}, {"tipo": "X", "fixo": None, "maximo": 16},), 'separador': True, 'regex': "(0)(\\d{13})([!%-?A-Z_a-z\\x22]{0,16})"},
    '8004': {'formato': "N4+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '8005': {'formato': "N4+N6", 'fixo': 6, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 6, "maximo": None},), 'separador': True, 'regex': "(\\d{6})"},
    '8006': {'formato': "N4+N14+N2+N2", 'fixo': 2, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 14, "maximo": None}, {"tipo": "N", "fixo": 2, "maximo": None}, {"tipo": "N", "fixo": 2, "maximo": None},), 'separador': True, 'regex': "(\\d{14})(\\d{4})"},
    '8007': {'formato': "N4+X..34", 'fixo': None, 'maximo': 34, 'campos': ({"tipo": "X", "fixo": None, "maximo": 34},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,34})"},
    '8008': {'formato': "N4+N8[+N..4]", 'fixo': None, 'maximo': 4, 'campos': ({"tipo": "N", "fixo": 8, "maximo": None}, {"tipo": "N", "fixo": None, "maximo": 4},), 'separador': True, 'regex': "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01])(?:[01]\\d|2[0-3]))((?:[0-5]\\d)(?:[0-5]\\d)?)?"},
    '8009': {'formato': "N4+X..50", 'fixo': None, 'maximo': 50, 'campos': ({"tipo": "X", "fixo": None, "maximo": 50},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,50})"},
    '8010': {'formato': "N4+Y..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "Y", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([A-Z0-9/#-]{5,30})"},
    '8011': {'formato': "N4+N..12", 'fixo': None, 'maximo': 12, 'campos': ({"tipo": "N", "fixo": None, "maximo": 12},), 'separador': True, 'regex': "(\\d{1,12})"},
    '8012': {'formato': "N4+X..20", 'fixo': None, 'maximo': 20, 'campos': ({"tipo": "X", "fixo": None, "maximo": 20},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,20})"},
    '8013': {'formato': "N4+X..25", 'fixo': None, 'maximo': 25, 'campos': ({"tipo": "X", "fixo": None, "maximo": 25},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,25})"},
    '8014': {'formato': "N4+X..25", 'fixo': None, 'maximo': 25, 'campos': ({"tipo": "X", "fixo": None, "maximo": 25},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,25})"},
    '8017': {'formato': "N4+N18", 'fixo': 18, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 18, "maximo": None},), 'separador': True, 'regex': "(\\d{18})"},
    '8018': {'formato': "N4+N18", 'fixo': 18, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 18, "maximo": None},), 'separador': True, 'regex': "(\\d{18})"},
    '8019': {'formato': "N4+N..10", 'fixo': None, 'maximo': 10, 'campos': ({"tipo": "N", "fixo": None, "maximo": 10},), 'separador': True, 'regex': "(\\d{1,10})"},
    '8020': {'formato': "N4+X..25", 'fixo': None, 'maximo': 25, 'campos': ({"tipo": "X", "fixo": None, "maximo": 25},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,25})"},
    '8026': {'formato': "N4+N14+N2+N2", 'fixo': 2, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 14, "maximo": None}, {"tipo": "N", "fixo": 2, "maximo": None}, {"tipo": "N", "fixo": 2, "maximo": None},), 'separador': True, 'regex': "(\\d{14})(\\d{4})"},
    '8030': {'formato': "N4+Z..90", 'fixo': None, 'maximo': 90, 'campos': ({"tipo": "Z", "fixo": None, "maximo": 90},), 'separador': True, 'regex': "([0-9A-Za-z_-]{1,90})"},
    '8040': {'formato': "N4+N15", 'fixo': 15, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 15, "maximo": None},), 'separador': True, 'regex': "(\\d{15})"},
    '8041': {'formato': "N4+N15", 'fixo': 15, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 15, "maximo": None},), 'separador': True, 'regex': "(\\d{15})"},
    '8042': {'formato': "N4+N32", 'fixo': 32, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 32, "maximo": None},), 'separador': True, 'regex': "(\\d{32})"},
    '8043': {'formato': "N4+N18+[N1..N2]", 'fixo': 2, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 18, "maximo": None}, {"tipo": "N", "fixo": 1, "maximo": None}, {"tipo": "N", "fixo": 2, "maximo": None},), 'separador': True, 'regex': "(\\d{18,20})"},
    '8110': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,70})"},
    '8111': {'formato': "N4+N4", 'fixo': 4, 'maximo': None, 'campos': ({"tipo": "N", "fixo": 4, "maximo": None},), 'separador': True, 'regex': "(\\d{4})"},
    '8112': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,70})"},
    '8200': {'formato': "N4+X..70", 'fixo': None, 'maximo': 70, 'campos': ({"tipo": "X", "fixo": None, "maximo": 70},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,70})"},
    '90': {'formato': "N2+X..30", 'fixo': None, 'maximo': 30, 'campos': ({"tipo": "X", "fixo": None, "maximo": 30},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,30})"},
    '91': {'formato': "N2+X..90", 'fixo': None, 'maximo': 90, 'campos': ({"tipo": "X", "fixo": None, "maximo": 90},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,90})"},
    '92': {'formato': "N2+X..90", 'fixo': None, 'maximo': 90, 'campos': ({"tipo": "X", "fixo": None, "maximo": 90},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,90})"},
    '93': {'formato': "N2+X..90", 'fixo': None, 'maximo': 90, 'campos': ({"tipo": "X", "fixo": None, "maximo": 90},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,90})"},
    '94': {'formato': "N2+X..90", 'fixo': None, 'maximo': 90, 'campos': ({"tipo": "X", "fixo": None, "maximo": 90},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,90})"},
    '95': {'formato': "N2+X..90", 'fixo': None, 'maximo': 90, 'campos': ({"tipo": "X", "fixo": None, "maximo": 90},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,90})"},
    '96': {'formato': "N2+X..90", 'fixo': None, 'maximo': 90, 'campos': ({"tipo": "X", "fixo": None, "maximo": 90},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,90})"},
    '97': {'formato': "N2+X..90", 'fixo': None, 'maximo': 90, 'campos': ({"tipo": "X", "fixo": None, "maximo": 90},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,90})"},
    '98': {'formato': "N2+X..90", 'fixo': None, 'maximo': 90, 'campos': ({"tipo": "X", "fixo": None, "maximo": 90},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,90})"},
    '99': {'formato': "N2+X..90", 'fixo': None, 'maximo': 90, 'campos': ({"tipo": "X", "fixo": None, "maximo": 90},), 'separador': True, 'regex': "([!%-?A-Z_a-z\\x22]{1,90})"},
}


def ai_de(numero: str) -> dict | None:
    """
    O AI de um numero, ou ``None`` se esse numero nao existe.

    Procura pelo AI mais comprido primeiro, e nao pelo mais curto.

    **Nao e' por causa de um caso que exista hoje.** Ha AIs de dois, de tres e de
    quatro digitos ao mesmo tempo, e nenhum e' prefixo de outro — o que o teste
    confirma. A ordem errada seria um seguro contra o dia em que a GS1 publicar um
    ``010``: a procura pelo mais curto leria-o como o AI ``01`` seguido de ``0``, e
    produzia um codigo com o GTIN partido ao meio e um leitor que nao diz nada.
    """
    entrada = AIS.get(numero)
    if entrada is not None:
        return {"numero": numero, **entrada}

    # Corta o ultimo digito ate dar, que e' a forma de tentar 4, 3 e 2.
    for n in range(len(numero) - 1, 1, -1):
        prefixo = numero[:n]
        entrada = AIS.get(prefixo)
        if entrada is not None:
            return {"numero": prefixo, "resto": numero[n:], **entrada}

    return None


#: Todos os AIs, para a interface os mostrar.
LISTA_AIS = sorted(AIS)
