/**
 * A tabela de Application Identifiers do GS1. Gerado por
 * ``spec/gerar-tabelas-gs1.py` a partir do JSON-LD de ref.gs1.org.
 * * A origem e' https://ref.gs1.org/ai/?lang=en, e fica escrita aqui porque uma tabela sem
 * origem e' uma tabela em que ninguem pode confiar.
 */

/** Os AIs, por numero. Um objeto em vez de uma lista porque se procura por
 * numero e nao se percorre - e porque o ficheiro tem de ficar legivel quando
 * alguem abrir para ver o que ha la dentro. As chaves sao `'01'` e nao `01`,
 * porque um numero em JavaScript perde o zero a esquerda. */
export const AIS = {
  '00': { f: "N2+N18", fixo: 18, maximo: null, campos: [{ t: 'N', f: 18, m: null }], sep: false, re: "(\\d{18})" },
  '01': { f: "N2+N14", fixo: 14, maximo: null, campos: [{ t: 'N', f: 14, m: null }], sep: false, re: "(\\d{14})" },
  '02': { f: "N2+N14", fixo: 14, maximo: null, campos: [{ t: 'N', f: 14, m: null }], sep: false, re: "(\\d{14})" },
  '03': { f: "N2+N14", fixo: 14, maximo: null, campos: [{ t: 'N', f: 14, m: null }], sep: false, re: "(\\d{14})" },
  '10': { f: "N2+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '11': { f: "N2+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))" },
  '12': { f: "N2+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))" },
  '13': { f: "N2+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))" },
  '15': { f: "N2+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))" },
  '16': { f: "N2+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))" },
  '17': { f: "N2+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))" },
  '20': { f: "N2+N2", fixo: 2, maximo: null, campos: [{ t: 'N', f: 2, m: null }], sep: false, re: "(\\d{2})" },
  '21': { f: "N2+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '22': { f: "N2+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '235': { f: "N3+X..28", fixo: null, maximo: 28, campos: [{ t: 'X', f: null, m: 28 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,28})" },
  '240': { f: "N3+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '241': { f: "N3+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '242': { f: "N3+N..6", fixo: null, maximo: 6, campos: [{ t: 'N', f: null, m: 6 }], sep: true, re: "(\\d{1,6})" },
  '243': { f: "N3+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '250': { f: "N3+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '251': { f: "N3+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '253': { f: "N3+N13[+X..17]", fixo: null, maximo: 17, campos: [{ t: 'N', f: 13, m: null }, { t: 'X', f: null, m: 17 }], sep: true, re: "(\\d{13})([!%-?A-Z_a-z\\x22]{0,17})" },
  '254': { f: "N3+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '255': { f: "N3+N13[+N..12]", fixo: null, maximo: 12, campos: [{ t: 'N', f: 13, m: null }, { t: 'N', f: null, m: 12 }], sep: true, re: "(\\d{13})(\\d{0,12})" },
  '30': { f: "N2+N..8", fixo: null, maximo: 8, campos: [{ t: 'N', f: null, m: 8 }], sep: true, re: "(\\d{0,8})" },
  '3100': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3101': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3102': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3103': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3104': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3105': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3110': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3111': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3112': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3113': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3114': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3115': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3120': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3121': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3122': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3123': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3124': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3125': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3130': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3131': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3132': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3133': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3134': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3135': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3140': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3141': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3142': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3143': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3144': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3145': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3150': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3151': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3152': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3153': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3154': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3155': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3160': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3161': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3162': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3163': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3164': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3165': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3200': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3201': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3202': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3203': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3204': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3205': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3210': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3211': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3212': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3213': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3214': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3215': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3220': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3221': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3222': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3223': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3224': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3225': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3230': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3231': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3232': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3233': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3234': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3235': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3240': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3241': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3242': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3243': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3244': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3245': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3250': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3251': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3252': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3253': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3254': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3255': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3260': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3261': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3262': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3263': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3264': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3265': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3270': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3271': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3272': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3273': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3274': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3275': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3280': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3281': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3282': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3283': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3284': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3285': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3290': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3291': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3292': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3293': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3294': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3295': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3300': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3301': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3302': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3303': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3304': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3305': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3310': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3311': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3312': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3313': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3314': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3315': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3320': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3321': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3322': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3323': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3324': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3325': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3330': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3331': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3332': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3333': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3334': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3335': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3340': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3341': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3342': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3343': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3344': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3345': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3350': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3351': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3352': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3353': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3354': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3355': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3360': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3361': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3362': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3363': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3364': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3365': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3370': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3371': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3372': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3373': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3374': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3375': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3400': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3401': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3402': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3403': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3404': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3405': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3410': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3411': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3412': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3413': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3414': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3415': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3420': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3421': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3422': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3423': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3424': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3425': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3430': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3431': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3432': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3433': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3434': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3435': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3440': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3441': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3442': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3443': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3444': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3445': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3450': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3451': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3452': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3453': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3454': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3455': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3460': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3461': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3462': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3463': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3464': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3465': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3470': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3471': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3472': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3473': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3474': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3475': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3480': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3481': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3482': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3483': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3484': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3485': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3490': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3491': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3492': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3493': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3494': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3495': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3500': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3501': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3502': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3503': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3504': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3505': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3510': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3511': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3512': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3513': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3514': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3515': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3520': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3521': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3522': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3523': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3524': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3525': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3530': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3531': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3532': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3533': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3534': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3535': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3540': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3541': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3542': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3543': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3544': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3545': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3550': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3551': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3552': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3553': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3554': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3555': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3560': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3561': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3562': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3563': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3564': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3565': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3570': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3571': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3572': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3573': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3574': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3575': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3600': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3601': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3602': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3603': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3604': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3605': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3610': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3611': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3612': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3613': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3614': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3615': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3620': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3621': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3622': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3623': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3624': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3625': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3630': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3631': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3632': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3633': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3634': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3635': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3640': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3641': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3642': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3643': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3644': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3645': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3650': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3651': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3652': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3653': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3654': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3655': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3660': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3661': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3662': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3663': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3664': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3665': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3670': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3671': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3672': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3673': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3674': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3675': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3680': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3681': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3682': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3683': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3684': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3685': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3690': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3691': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3692': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3693': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3694': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '3695': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: false, re: "(\\d{6})" },
  '37': { f: "N2+N..8", fixo: null, maximo: 8, campos: [{ t: 'N', f: null, m: 8 }], sep: true, re: "(\\d{1,8})" },
  '3900': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3901': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3902': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3903': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3904': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3905': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3906': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3907': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3908': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3909': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3910': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3911': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3912': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3913': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3914': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3915': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3916': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3917': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3918': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3919': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3920': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3921': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3922': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3923': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3924': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3925': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3926': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3927': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3928': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3929': { f: "N4+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{1,15})" },
  '3930': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3931': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3932': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3933': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3934': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3935': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3936': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3937': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3938': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3939': { f: "N4+N3+N..15", fixo: null, maximo: 15, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 15 }], sep: true, re: "(\\d{3})(\\d{1,15})" },
  '3940': { f: "N4+N4", fixo: 4, maximo: null, campos: [{ t: 'N', f: 4, m: null }], sep: true, re: "(\\d{4})" },
  '3941': { f: "N4+N4", fixo: 4, maximo: null, campos: [{ t: 'N', f: 4, m: null }], sep: true, re: "(\\d{4})" },
  '3942': { f: "N4+N4", fixo: 4, maximo: null, campos: [{ t: 'N', f: 4, m: null }], sep: true, re: "(\\d{4})" },
  '3943': { f: "N4+N4", fixo: 4, maximo: null, campos: [{ t: 'N', f: 4, m: null }], sep: true, re: "(\\d{4})" },
  '3950': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6})" },
  '3951': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6})" },
  '3952': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6})" },
  '3953': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6})" },
  '3954': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6})" },
  '3955': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6})" },
  '400': { f: "N3+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '401': { f: "N3+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '402': { f: "N3+N17", fixo: 17, maximo: null, campos: [{ t: 'N', f: 17, m: null }], sep: true, re: "(\\d{17})" },
  '403': { f: "N3+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '410': { f: "N3+N13", fixo: 13, maximo: null, campos: [{ t: 'N', f: 13, m: null }], sep: false, re: "(\\d{13})" },
  '411': { f: "N3+N13", fixo: 13, maximo: null, campos: [{ t: 'N', f: 13, m: null }], sep: false, re: "(\\d{13})" },
  '412': { f: "N3+N13", fixo: 13, maximo: null, campos: [{ t: 'N', f: 13, m: null }], sep: false, re: "(\\d{13})" },
  '413': { f: "N3+N13", fixo: 13, maximo: null, campos: [{ t: 'N', f: 13, m: null }], sep: false, re: "(\\d{13})" },
  '414': { f: "N3+N13", fixo: 13, maximo: null, campos: [{ t: 'N', f: 13, m: null }], sep: false, re: "(\\d{13})" },
  '415': { f: "N3+N13", fixo: 13, maximo: null, campos: [{ t: 'N', f: 13, m: null }], sep: false, re: "(\\d{13})" },
  '416': { f: "N3+N13", fixo: 13, maximo: null, campos: [{ t: 'N', f: 13, m: null }], sep: false, re: "(\\d{13})" },
  '417': { f: "N3+N13", fixo: 13, maximo: null, campos: [{ t: 'N', f: 13, m: null }], sep: false, re: "(\\d{13})" },
  '420': { f: "N3+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '421': { f: "N3+N3+X..9", fixo: null, maximo: 9, campos: [{ t: 'N', f: 3, m: null }, { t: 'X', f: null, m: 9 }], sep: true, re: "(\\d{3})([!%-?A-Z_a-z\\x22]{1,9})" },
  '422': { f: "N3+N3", fixo: 3, maximo: null, campos: [{ t: 'N', f: 3, m: null }], sep: true, re: "(\\d{3})" },
  '423': { f: "N3+N3+N..12", fixo: null, maximo: 12, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 12 }], sep: true, re: "((?:\\d{3}){1,5})" },
  '424': { f: "N3+N3", fixo: 3, maximo: null, campos: [{ t: 'N', f: 3, m: null }], sep: true, re: "(\\d{3})" },
  '425': { f: "N3+N3+N..12", fixo: null, maximo: 12, campos: [{ t: 'N', f: 3, m: null }, { t: 'N', f: null, m: 12 }], sep: true, re: "((?:\\d{3}){1,5})" },
  '426': { f: "N3+N3", fixo: 3, maximo: null, campos: [{ t: 'N', f: 3, m: null }], sep: true, re: "(\\d{3})" },
  '427': { f: "N3+X..3", fixo: null, maximo: 3, campos: [{ t: 'X', f: null, m: 3 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,3})" },
  '4300': { f: "N4+X..35", fixo: null, maximo: 35, campos: [{ t: 'X', f: null, m: 35 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})" },
  '4301': { f: "N4+X..35", fixo: null, maximo: 35, campos: [{ t: 'X', f: null, m: 35 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})" },
  '4302': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})" },
  '4303': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})" },
  '4304': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})" },
  '4305': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})" },
  '4306': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})" },
  '4307': { f: "N4+X2", fixo: 2, maximo: null, campos: [{ t: 'X', f: 2, m: null }], sep: true, re: "([A-Z0-9]{2})" },
  '4308': { f: "N4+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '4309': { f: "N4+N20", fixo: 20, maximo: null, campos: [{ t: 'N', f: 20, m: null }], sep: true, re: "(\\d{20})" },
  '4310': { f: "N4+X..35", fixo: null, maximo: 35, campos: [{ t: 'X', f: null, m: 35 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})" },
  '4311': { f: "N4+X..35", fixo: null, maximo: 35, campos: [{ t: 'X', f: null, m: 35 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})" },
  '4312': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})" },
  '4313': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})" },
  '4314': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})" },
  '4315': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})" },
  '4316': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})" },
  '4317': { f: "N4+X2", fixo: 2, maximo: null, campos: [{ t: 'X', f: 2, m: null }], sep: true, re: "([A-Z0-9]{2})" },
  '4318': { f: "N4+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '4319': { f: "N4+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '4320': { f: "N4+X..35", fixo: null, maximo: 35, campos: [{ t: 'X', f: null, m: 35 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})" },
  '4321': { f: "N4+N1", fixo: 1, maximo: null, campos: [{ t: 'N', f: 1, m: null }], sep: true, re: "([01])" },
  '4322': { f: "N4+N1", fixo: 1, maximo: null, campos: [{ t: 'N', f: 1, m: null }], sep: true, re: "([01])" },
  '4323': { f: "N4+N1", fixo: 1, maximo: null, campos: [{ t: 'N', f: 1, m: null }], sep: true, re: "([01])" },
  '4324': { f: "N4+N10", fixo: 10, maximo: null, campos: [{ t: 'N', f: 10, m: null }], sep: true, re: "(\\d{10})" },
  '4325': { f: "N4+N10", fixo: 10, maximo: null, campos: [{ t: 'N', f: 10, m: null }], sep: true, re: "(\\d{10})" },
  '4326': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6})" },
  '4330': { f: "N4+N6+[-]", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6}[-]?)" },
  '4331': { f: "N4+N6+[-]", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6}[-]?)" },
  '4332': { f: "N4+N6+[-]", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6}[-]?)" },
  '4333': { f: "N4+N6+[-]", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6}[-]?)" },
  '7001': { f: "N4+N13", fixo: 13, maximo: null, campos: [{ t: 'N', f: 13, m: null }], sep: true, re: "(\\d{13})" },
  '7002': { f: "N4+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '7003': { f: "N4+N10", fixo: 10, maximo: null, campos: [{ t: 'N', f: 10, m: null }], sep: true, re: "(\\d{10})" },
  '7004': { f: "N4+N..4", fixo: null, maximo: 4, campos: [{ t: 'N', f: null, m: 4 }], sep: true, re: "(\\d{0,4})" },
  '7005': { f: "N4+X..12", fixo: null, maximo: 12, campos: [{ t: 'X', f: null, m: 12 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,12})" },
  '7006': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6})" },
  '7007': { f: "N4+N6[+N6]", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }, { t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6})(\\d{6})?" },
  '7008': { f: "N4+X..3", fixo: null, maximo: 3, campos: [{ t: 'X', f: null, m: 3 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,3})" },
  '7009': { f: "N4+X..10", fixo: null, maximo: 10, campos: [{ t: 'X', f: null, m: 10 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,10})" },
  '7010': { f: "N4+X..2", fixo: null, maximo: 2, campos: [{ t: 'X', f: null, m: 2 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,2})" },
  '7011': { f: "N4+N6[+N4]", fixo: 4, maximo: null, campos: [{ t: 'N', f: 6, m: null }, { t: 'N', f: 4, m: null }], sep: true, re: "(\\d{6})(\\d{4})?" },
  '7020': { f: "N4+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '7021': { f: "N4+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '7022': { f: "N4+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '7023': { f: "N4+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '7030': { f: "N4+N3+X..27", fixo: null, maximo: 27, campos: [{ t: 'N', f: 3, m: null }, { t: 'X', f: null, m: 27 }], sep: true, re: "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})" },
  '7031': { f: "N4+N3+X..27", fixo: null, maximo: 27, campos: [{ t: 'N', f: 3, m: null }, { t: 'X', f: null, m: 27 }], sep: true, re: "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})" },
  '7032': { f: "N4+N3+X..27", fixo: null, maximo: 27, campos: [{ t: 'N', f: 3, m: null }, { t: 'X', f: null, m: 27 }], sep: true, re: "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})" },
  '7033': { f: "N4+N3+X..27", fixo: null, maximo: 27, campos: [{ t: 'N', f: 3, m: null }, { t: 'X', f: null, m: 27 }], sep: true, re: "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})" },
  '7034': { f: "N4+N3+X..27", fixo: null, maximo: 27, campos: [{ t: 'N', f: 3, m: null }, { t: 'X', f: null, m: 27 }], sep: true, re: "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})" },
  '7035': { f: "N4+N3+X..27", fixo: null, maximo: 27, campos: [{ t: 'N', f: 3, m: null }, { t: 'X', f: null, m: 27 }], sep: true, re: "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})" },
  '7036': { f: "N4+N3+X..27", fixo: null, maximo: 27, campos: [{ t: 'N', f: 3, m: null }, { t: 'X', f: null, m: 27 }], sep: true, re: "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})" },
  '7037': { f: "N4+N3+X..27", fixo: null, maximo: 27, campos: [{ t: 'N', f: 3, m: null }, { t: 'X', f: null, m: 27 }], sep: true, re: "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})" },
  '7038': { f: "N4+N3+X..27", fixo: null, maximo: 27, campos: [{ t: 'N', f: 3, m: null }, { t: 'X', f: null, m: 27 }], sep: true, re: "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})" },
  '7039': { f: "N4+N3+X..27", fixo: null, maximo: 27, campos: [{ t: 'N', f: 3, m: null }, { t: 'X', f: null, m: 27 }], sep: true, re: "(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})" },
  '7040': { f: "N4+N1+X3", fixo: 3, maximo: null, campos: [{ t: 'N', f: 1, m: null }, { t: 'X', f: 3, m: null }], sep: true, re: "(\\d)([!%-?A-Z_a-z\\x22])([!%-?A-Z_a-z\\x22])([!%-?A-Z_a-z\\x22])" },
  '7041': { f: "N4+X..4", fixo: null, maximo: 4, campos: [{ t: 'X', f: null, m: 4 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,4})" },
  '710': { f: "N3+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '711': { f: "N3+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '712': { f: "N3+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '713': { f: "N3+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '714': { f: "N3+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '715': { f: "N3+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '716': { f: "N3+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '717': { f: "N3+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '7230': { f: "N4+X2+X..28", fixo: null, maximo: 28, campos: [{ t: 'X', f: 2, m: null }, { t: 'X', f: null, m: 28 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{3,30})" },
  '7231': { f: "N4+X2+X..28", fixo: null, maximo: 28, campos: [{ t: 'X', f: 2, m: null }, { t: 'X', f: null, m: 28 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{3,30})" },
  '7232': { f: "N4+X2+X..28", fixo: null, maximo: 28, campos: [{ t: 'X', f: 2, m: null }, { t: 'X', f: null, m: 28 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{3,30})" },
  '7233': { f: "N4+X2+X..28", fixo: null, maximo: 28, campos: [{ t: 'X', f: 2, m: null }, { t: 'X', f: null, m: 28 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{3,30})" },
  '7234': { f: "N4+X2+X..28", fixo: null, maximo: 28, campos: [{ t: 'X', f: 2, m: null }, { t: 'X', f: null, m: 28 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{3,30})" },
  '7235': { f: "N4+X2+X..28", fixo: null, maximo: 28, campos: [{ t: 'X', f: 2, m: null }, { t: 'X', f: null, m: 28 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{3,30})" },
  '7236': { f: "N4+X2+X..28", fixo: null, maximo: 28, campos: [{ t: 'X', f: 2, m: null }, { t: 'X', f: null, m: 28 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{3,30})" },
  '7237': { f: "N4+X2+X..28", fixo: null, maximo: 28, campos: [{ t: 'X', f: 2, m: null }, { t: 'X', f: null, m: 28 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{3,30})" },
  '7238': { f: "N4+X2+X..28", fixo: null, maximo: 28, campos: [{ t: 'X', f: 2, m: null }, { t: 'X', f: null, m: 28 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{3,30})" },
  '7239': { f: "N4+X2+X..28", fixo: null, maximo: 28, campos: [{ t: 'X', f: 2, m: null }, { t: 'X', f: null, m: 28 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{3,30})" },
  '7240': { f: "N4+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '7241': { f: "N4+N2", fixo: 2, maximo: null, campos: [{ t: 'N', f: 2, m: null }], sep: true, re: "(\\d{2})" },
  '7242': { f: "N4+X..25", fixo: null, maximo: 25, campos: [{ t: 'X', f: null, m: 25 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,25})" },
  '7250': { f: "N4+N8", fixo: 8, maximo: null, campos: [{ t: 'N', f: 8, m: null }], sep: true, re: "(\\d{4}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))" },
  '7251': { f: "N4+N12", fixo: 12, maximo: null, campos: [{ t: 'N', f: 12, m: null }], sep: true, re: "(\\d{4}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01])(?:[01]\\d|2[0-3])(?:[0-5]\\d))" },
  '7252': { f: "N4+N1", fixo: 1, maximo: null, campos: [{ t: 'N', f: 1, m: null }], sep: true, re: "(\\d{1})" },
  '7253': { f: "N4+X..40", fixo: null, maximo: 40, campos: [{ t: 'X', f: null, m: 40 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,40})" },
  '7254': { f: "N4+X..40", fixo: null, maximo: 40, campos: [{ t: 'X', f: null, m: 40 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,40})" },
  '7255': { f: "N4+X..10", fixo: null, maximo: 10, campos: [{ t: 'X', f: null, m: 10 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,10})" },
  '7256': { f: "N4+X..90", fixo: null, maximo: 90, campos: [{ t: 'X', f: null, m: 90 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,90})" },
  '7257': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})" },
  '7258': { f: "N4+N1+X1+N1", fixo: 1, maximo: null, campos: [{ t: 'N', f: 1, m: null }, { t: 'X', f: 1, m: null }, { t: 'N', f: 1, m: null }], sep: true, re: "(\\d[/]\\d)" },
  '7259': { f: "N4+X..40", fixo: null, maximo: 40, campos: [{ t: 'X', f: null, m: 40 }], sep: true, re: "((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,40})" },
  '8001': { f: "N4+N14", fixo: 14, maximo: null, campos: [{ t: 'N', f: 14, m: null }], sep: true, re: "(\\d{4})(\\d{5})(\\d{3})(\\d{1})(\\d{1})" },
  '8002': { f: "N4+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '8003': { f: "N4+N14[+X..16]", fixo: null, maximo: 16, campos: [{ t: 'N', f: 14, m: null }, { t: 'X', f: null, m: 16 }], sep: true, re: "(0)(\\d{13})([!%-?A-Z_a-z\\x22]{0,16})" },
  '8004': { f: "N4+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '8005': { f: "N4+N6", fixo: 6, maximo: null, campos: [{ t: 'N', f: 6, m: null }], sep: true, re: "(\\d{6})" },
  '8006': { f: "N4+N14+N2+N2", fixo: 2, maximo: null, campos: [{ t: 'N', f: 14, m: null }, { t: 'N', f: 2, m: null }, { t: 'N', f: 2, m: null }], sep: true, re: "(\\d{14})(\\d{4})" },
  '8007': { f: "N4+X..34", fixo: null, maximo: 34, campos: [{ t: 'X', f: null, m: 34 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,34})" },
  '8008': { f: "N4+N8[+N..4]", fixo: null, maximo: 4, campos: [{ t: 'N', f: 8, m: null }, { t: 'N', f: null, m: 4 }], sep: true, re: "(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01])(?:[01]\\d|2[0-3]))((?:[0-5]\\d)(?:[0-5]\\d)?)?" },
  '8009': { f: "N4+X..50", fixo: null, maximo: 50, campos: [{ t: 'X', f: null, m: 50 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,50})" },
  '8010': { f: "N4+Y..30", fixo: null, maximo: 30, campos: [{ t: 'Y', f: null, m: 30 }], sep: true, re: "([A-Z0-9/#-]{5,30})" },
  '8011': { f: "N4+N..12", fixo: null, maximo: 12, campos: [{ t: 'N', f: null, m: 12 }], sep: true, re: "(\\d{1,12})" },
  '8012': { f: "N4+X..20", fixo: null, maximo: 20, campos: [{ t: 'X', f: null, m: 20 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,20})" },
  '8013': { f: "N4+X..25", fixo: null, maximo: 25, campos: [{ t: 'X', f: null, m: 25 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,25})" },
  '8014': { f: "N4+X..25", fixo: null, maximo: 25, campos: [{ t: 'X', f: null, m: 25 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,25})" },
  '8017': { f: "N4+N18", fixo: 18, maximo: null, campos: [{ t: 'N', f: 18, m: null }], sep: true, re: "(\\d{18})" },
  '8018': { f: "N4+N18", fixo: 18, maximo: null, campos: [{ t: 'N', f: 18, m: null }], sep: true, re: "(\\d{18})" },
  '8019': { f: "N4+N..10", fixo: null, maximo: 10, campos: [{ t: 'N', f: null, m: 10 }], sep: true, re: "(\\d{1,10})" },
  '8020': { f: "N4+X..25", fixo: null, maximo: 25, campos: [{ t: 'X', f: null, m: 25 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,25})" },
  '8026': { f: "N4+N14+N2+N2", fixo: 2, maximo: null, campos: [{ t: 'N', f: 14, m: null }, { t: 'N', f: 2, m: null }, { t: 'N', f: 2, m: null }], sep: true, re: "(\\d{14})(\\d{4})" },
  '8030': { f: "N4+Z..90", fixo: null, maximo: 90, campos: [{ t: 'Z', f: null, m: 90 }], sep: true, re: "([0-9A-Za-z_-]{1,90})" },
  '8040': { f: "N4+N15", fixo: 15, maximo: null, campos: [{ t: 'N', f: 15, m: null }], sep: true, re: "(\\d{15})" },
  '8041': { f: "N4+N15", fixo: 15, maximo: null, campos: [{ t: 'N', f: 15, m: null }], sep: true, re: "(\\d{15})" },
  '8042': { f: "N4+N32", fixo: 32, maximo: null, campos: [{ t: 'N', f: 32, m: null }], sep: true, re: "(\\d{32})" },
  '8043': { f: "N4+N18+[N1..N2]", fixo: 2, maximo: null, campos: [{ t: 'N', f: 18, m: null }, { t: 'N', f: 1, m: null }, { t: 'N', f: 2, m: null }], sep: true, re: "(\\d{18,20})" },
  '8110': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,70})" },
  '8111': { f: "N4+N4", fixo: 4, maximo: null, campos: [{ t: 'N', f: 4, m: null }], sep: true, re: "(\\d{4})" },
  '8112': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,70})" },
  '8200': { f: "N4+X..70", fixo: null, maximo: 70, campos: [{ t: 'X', f: null, m: 70 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,70})" },
  '90': { f: "N2+X..30", fixo: null, maximo: 30, campos: [{ t: 'X', f: null, m: 30 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,30})" },
  '91': { f: "N2+X..90", fixo: null, maximo: 90, campos: [{ t: 'X', f: null, m: 90 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,90})" },
  '92': { f: "N2+X..90", fixo: null, maximo: 90, campos: [{ t: 'X', f: null, m: 90 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,90})" },
  '93': { f: "N2+X..90", fixo: null, maximo: 90, campos: [{ t: 'X', f: null, m: 90 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,90})" },
  '94': { f: "N2+X..90", fixo: null, maximo: 90, campos: [{ t: 'X', f: null, m: 90 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,90})" },
  '95': { f: "N2+X..90", fixo: null, maximo: 90, campos: [{ t: 'X', f: null, m: 90 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,90})" },
  '96': { f: "N2+X..90", fixo: null, maximo: 90, campos: [{ t: 'X', f: null, m: 90 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,90})" },
  '97': { f: "N2+X..90", fixo: null, maximo: 90, campos: [{ t: 'X', f: null, m: 90 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,90})" },
  '98': { f: "N2+X..90", fixo: null, maximo: 90, campos: [{ t: 'X', f: null, m: 90 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,90})" },
  '99': { f: "N2+X..90", fixo: null, maximo: 90, campos: [{ t: 'X', f: null, m: 90 }], sep: true, re: "([!%-?A-Z_a-z\\x22]{1,90})" },
};


/**
 * O AI de um numero, ou `null` se esse numero nao existe.
 *
 * Procura pelo AI mais comprido primeiro, e nao pelo mais curto.
 *
 * **Nao e' por causa de um caso que exista hoje.** Ha AIs de dois, de tres e de
 * quatro digitos ao mesmo tempo, e nenhum e' prefixo de outro — o que o teste
 * confirma. A ordem errada seria um seguro contra o dia em que a GS1 publicar um
 * `010`: a procura pelo mais curto leria-o como o AI `01` seguido de `0`, e
 * produzia um codigo com o GTIN partido ao meio e um leitor que nao diz nada.
 */
export function aiDe(numero) {
  if (AIS[numero]) return { numero, ...AIS[numero] };

  // Corta o ultimo digito ate dar, que e' a forma de tentar 4, 3 e 2.
  for (let n = numero.length - 1; n >= 2; n--) {
    const prefixo = numero.slice(0, n);
    if (AIS[prefixo]) return { numero: prefixo, resto: numero.slice(n), ...AIS[prefixo] };
  }

  return null;
}

/** Todos os AIs, para a interface os mostrar. */
export const LISTA_AIS = Object.keys(AIS).sort();
